---
# tasks file for roles/database
- name: Install MariaDB
  dnf:
    name: mariadb-server
    state: present


- name: Start MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes     
